{% set name = "huggingface_hub" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/huggingface_hub-{{ version }}.tar.gz
  sha256: 8154dc2fad84b32a4bca18372a647d9381ed8550a80b11050758357b8fcea639

build:
  number: 0
  noarch: python
  entry_points:
    - huggingface-cli=huggingface_hub.commands.huggingface_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.0
  run:
    - filelock
    - python >=3.7.0
    - pyyaml >=5.1
    - packaging >=20.9
    - requests
    - tqdm
    - typing-extensions >=3.7.4.3
    # Only required for [py<38] but always include so this can be noarch: python
    - importlib_metadata
  run_constrained:
    - fastai >=2.4
    - fastcore >=1.3.27

test:
  imports:
    - huggingface_hub
    - huggingface_hub.commands
  commands:
    - pip check
    - huggingface-cli --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models on the huggingface.co hub
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LysandreJik
    - osanseviero
    - adrinjalali
    - BastianZim
